env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 12
rules:
  prettier/prettier: 0
  global-require: error
  func-names: "off"
  no-underscore-dangle: "off"
  no-plusplus: ["warn", { "allowForLoopAfterthoughts": true }]
  brace-style:
    - error
    - 1tbs
  semi:
    - error
    - never
  eqeqeq: "off"
  array-callback-return: "off"
  arrow-parens: ["error", "as-needed"]
  no-param-reassign:
    - error
    - props: false
  no-return-assign: "off"
  no-unused-vars:
    - error
    - varsIgnorePattern: debug
